version: '3'
services:
  querier-server:
    image: git-ogbu-reg.gov74.ru/express
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3080:3080"
    container_name: express
    volumes:
       - ./server:/server/
       - /server/node_modules
  querier-ui:
    depends_on:
      - querier-server
    image: git-ogbu-reg.gov74.ru/vue
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    container_name: vue
    volumes:
       - ./client:/client
       - /client/node_modules